apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-backend-deployment
  labels:
    app: twitter-backend-application
spec:
  replicas: 1
  selector:
    matchLabels:
      component: twitter-backend-microservice
  template:
    metadata:
      labels:
        component: twitter-backend-microservice
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: twitter-backend-microservice
          image: registry.gitlab.com/lutik/twitter:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '130m'
              memory: '200M'
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: twitter-service
spec:
  type: NodePort
  selector:
    component: twitter-backend-microservice
  ports:
    - port: 3000
      targetPort: 5000
